# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/helper/UI/aboutDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(359, 376)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/app_blue.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(100, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/app_blue.ico"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p style=\"line-height:0.5\"><span style=\" font-size:10pt; font-weight:600;\">关于专利审查助手helper</span></p><p style=\"line-height:0.5\"><span style=\" font-weight:600;\">版本信息</span></p><p style=\"line-height:0.5\"><span style=\" font-size:8pt;\">- 当前版本：0.1.0</span></p><p style=\"line-height:0.5\"><span style=\" font-size:8pt;\">- 更新日期：2024年11月23日</span></p><p style=\"line-height:0.5\"><span style=\" font-weight:600;\">版权信息</span></p><p style=\"line-height:0.5\"><span style=\" font-size:8pt;\">© 2024 卢振宇，保留所有权利 </span></p><p style=\"line-height:0.5\"><span style=\" font-weight:600;\">许可证信息</span></p><p style=\"line-height:0.5\"><span style=\" font-size:8pt;\">MIT许可证，<a href=\"https://mit-license.org/\">https://mit-license.org/</a></span></p><p style=\"line-height:0.5\"><span style=\" font-weight:600;\">第三方库和工具</span></p><p style=\"line-height:0.5\"><span style=\" font-size:8pt;\">我们的应用程序使用以下第三方库和工具： </span></p><p style=\"line-height:0.5\"><span style=\" font-size:8pt;\">1. Python - 一款流行的脚本程序</span></p><p style=\"line-height:0.5\"><span style=\" font-size:8pt;\">2. PyQt5 - Qt5 GUI框架的Python绑定库</span></p><p style=\"line-height:0.5\"><span style=\" font-size:9pt; font-weight:600;\">反馈途径</span></p><p style=\"line-height:0.5\"><span style=\" font-size:8pt;\">如果您遇到问题或发现Bug，请联系：</span></p><p style=\"line-height:0.5\"><span style=\" font-size:8pt;\">- 电子邮件：luzhenyu@cnipa.gov.cn</span></p><p style=\"line-height:0.5\"><span style=\" font-size:8pt;\">- 电话：0512-88995893</span></p></body></html>"))
import resources_rc
