# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/helper/UI/refDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_refDialog(object):
    def setupUi(self, refDialog):
        refDialog.setObjectName("refDialog")
        refDialog.resize(400, 300)
        refDialog.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/app_blue.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        refDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(refDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.refTextBrowser = QtWidgets.QTextBrowser(refDialog)
        self.refTextBrowser.setObjectName("refTextBrowser")
        self.verticalLayout.addWidget(self.refTextBrowser)
        self.buttonBox = QtWidgets.QDialogButtonBox(refDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(refDialog)
        self.buttonBox.accepted.connect(refDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(refDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(refDialog)

    def retranslateUi(self, refDialog):
        _translate = QtCore.QCoreApplication.translate
        refDialog.setWindowTitle(_translate("refDialog", "权利要求引用关系"))
from . import resources_rc
