# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/helper/UI/searchDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_searchDialog(object):
    def setupUi(self, searchDialog):
        searchDialog.setObjectName("searchDialog")
        searchDialog.resize(336, 123)
        searchDialog.setMinimumSize(QtCore.QSize(336, 123))
        searchDialog.setMaximumSize(QtCore.QSize(336, 123))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/search_blue.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        searchDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(searchDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(1)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(searchDialog)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.searchLineEdit = QtWidgets.QLineEdit(searchDialog)
        self.searchLineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.searchLineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.preButton = QtWidgets.QPushButton(searchDialog)
        self.preButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.preButton.setObjectName("preButton")
        self.horizontalLayout.addWidget(self.preButton)
        self.nextButton = QtWidgets.QPushButton(searchDialog)
        self.nextButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.repeatCheckBox = QtWidgets.QCheckBox(searchDialog)
        self.repeatCheckBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.repeatCheckBox.setObjectName("repeatCheckBox")
        self.gridLayout.addWidget(self.repeatCheckBox, 0, 0, 1, 1)
        self.regexCheckBox = QtWidgets.QCheckBox(searchDialog)
        self.regexCheckBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.regexCheckBox.setObjectName("regexCheckBox")
        self.gridLayout.addWidget(self.regexCheckBox, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(searchDialog)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(searchDialog)
        self.pushButton_3.clicked.connect(searchDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(searchDialog)

    def retranslateUi(self, searchDialog):
        _translate = QtCore.QCoreApplication.translate
        searchDialog.setWindowTitle(_translate("searchDialog", "查找"))
        self.label.setText(_translate("searchDialog", "查找："))
        self.preButton.setText(_translate("searchDialog", "查找上一个(P)"))
        self.preButton.setShortcut(_translate("searchDialog", "P"))
        self.nextButton.setText(_translate("searchDialog", "查找下一个(N)"))
        self.nextButton.setShortcut(_translate("searchDialog", "N"))
        self.repeatCheckBox.setText(_translate("searchDialog", "循环搜索"))
        self.regexCheckBox.setText(_translate("searchDialog", "使用正则表达式"))
        self.pushButton_3.setText(_translate("searchDialog", "取消(C)"))
        self.pushButton_3.setShortcut(_translate("searchDialog", "C"))
from . import resources_rc
